# Generated by Django 5.2.16 on 2026-07-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='1 to 5')),
                ('text', models.TextField()),
                ('video_url', models.URLField(blank=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Unapproved testimonials never appear on the public site.')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
