# Generated by Django 5.2.16 on 2026-07-15 10:16

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Package categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('short_description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('duration', models.CharField(blank=True, help_text='e.g. "6 Days / 5 Nights"', max_length=60)),
                ('itinerary', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Itinerary')),
                ('inclusions', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Inclusions')),
                ('exclusions', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Exclusions')),
                ('accommodation_details', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Accommodation')),
                ('transport_details', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Transport')),
                ('terms_and_conditions', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Terms & conditions')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_seasonal', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='tours.packagecategory')),
                ('destinations', models.ManyToManyField(blank=True, related_name='packages', to='destinations.destination')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='packages/gallery/')),
                ('caption', models.CharField(blank=True, max_length=180)),
                ('order', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.tourpackage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
