# Generated by Django 5.2.16 on 2026-07-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Swift / Aura"', max_length=120)),
                ('category', models.CharField(blank=True, help_text='e.g. "Sedan", "Premium SUV"', max_length=80)),
                ('seating', models.CharField(blank=True, help_text='e.g. "4 seats", "12–26 seats"', max_length=40)),
                ('per_km_rate', models.DecimalField(blank=True, decimal_places=0, help_text='Indicative per-km rate with driver, in ₹', max_digits=6, null=True)),
                ('best_for', models.CharField(blank=True, help_text='Short one-line description', max_length=180)),
                ('icon', models.CharField(default='fas fa-car', help_text='Font Awesome class, used when no image is uploaded', max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'per_km_rate'],
            },
        ),
    ]
