# Generated by Django 5.2.16 on 2026-07-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='e.g. "6000+", "4.8", "100%"', max_length=20)),
                ('label', models.CharField(help_text='e.g. "Happy Travellers"', max_length=60)),
                ('icon', models.CharField(default='fas fa-star', help_text="Font Awesome class, e.g. 'fas fa-users'", max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
