# Generated by Django 5.2.16 on 2026-07-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='icon',
            field=models.CharField(choices=[('fas fa-users', 'People / Travellers'), ('fas fa-star', 'Star / Rating'), ('fas fa-mountain-sun', 'Mountain'), ('fas fa-shield-heart', 'Shield (safety)'), ('fas fa-route', 'Route'), ('fas fa-award', 'Award / Badge'), ('fas fa-calendar-check', 'Calendar'), ('fas fa-map-location-dot', 'Map'), ('fas fa-car-side', 'Vehicle'), ('fas fa-headset', 'Support'), ('fas fa-thumbs-up', 'Thumbs up'), ('fas fa-heart', 'Heart'), ('fas fa-earth-asia', 'Globe'), ('fas fa-hotel', 'Hotel'), ('fas fa-person-hiking', 'Hiking')], default='fas fa-star', help_text='Pick an icon from the list', max_length=40),
        ),
    ]
