# Generated by Django 5.2.16 on 2026-07-30 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gallerycategory_galleryimage_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='logo',
            field=models.ImageField(blank=True, help_text='PNG only. Shows in the navbar and footer. Leave blank to use the default logo.', null=True, upload_to='site/', validators=[django.core.validators.FileExtensionValidator(['png'])]),
        ),
    ]
