# Generated by Django 5.2.16 on 2026-07-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_siteconfig_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='hero_badge',
            field=models.CharField(blank=True, default='Kedarnath · Badrinath', help_text='Small pill on the image corner. Leave blank to hide.', max_length=60),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_eyebrow',
            field=models.CharField(blank=True, default='Devbhoomi Uttarakhand', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_highlight',
            field=models.CharField(blank=True, default='sacred', help_text='A word/phrase inside the title to emphasise (clay italic). Must appear in the title.', max_length=60),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero banner image. Leave blank to use the default.', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_primary_label',
            field=models.CharField(default='Explore Packages', help_text='Left button (links to Packages).', max_length=40),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_rating',
            field=models.CharField(blank=True, default='4.8 · 6000+ travellers', help_text='Rating line under the buttons. Leave blank to hide.', max_length=60),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_secondary_label',
            field=models.CharField(default='Plan Your Journey', help_text='Right button (links to the enquiry form).', max_length=40),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_stat_label',
            field=models.CharField(blank=True, default='Guiding the Char Dham route', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_stat_value',
            field=models.CharField(blank=True, default='15+ yrs', max_length=30),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Safe, women-friendly, transparently priced pilgrimages and mountain tours — crafted by local experts who live in the valleys of Kedarnath.'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_title',
            field=models.CharField(default='Journeys to the sacred Himalayas.', help_text='Main headline.', max_length=160),
        ),
    ]
