# Generated by Django 5.2.16 on 2026-07-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='inquiry',
            name='destination',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='hotel_category',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='num_kids',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='No. of kids (below 5)'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='num_travellers',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='No. of travellers'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='vehicle_preference',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='source_type',
            field=models.CharField(choices=[('general', 'General'), ('package', 'Package'), ('booking', 'Booking request'), ('custom-tour', 'Custom tour'), ('callback', 'Callback'), ('whatsapp', 'WhatsApp')], default='general', max_length=20),
        ),
    ]
