# Generated by Django 5.2.16 on 2026-07-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_newslettersubscriber_inquiry_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='source_type',
            field=models.CharField(choices=[('general', 'General'), ('package', 'Package'), ('booking', 'Booking request'), ('rental', 'Vehicle rental'), ('custom-tour', 'Custom tour'), ('callback', 'Callback'), ('whatsapp', 'WhatsApp')], default='general', max_length=20),
        ),
    ]
