# Generated by Django 5.2.16 on 2026-07-15 10:16

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('overview', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Overview')),
                ('attractions', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Attractions')),
                ('travel_guide', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Travel guide')),
                ('best_time_to_visit', models.CharField(blank=True, max_length=200)),
                ('local_activities', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Local activities')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='destinations/')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='destinations/gallery/')),
                ('caption', models.CharField(blank=True, max_length=180)),
                ('order', models.PositiveIntegerField(default=0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='destinations.destination')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
